server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:task
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE
